Template for the profile page, Issue #9
MLH-Fellowship/prep-portfolio-23.MAR.PREP.1 pull request #27
Opened 2023-03-10 07:22 UTC by 2leila5

## Please, go through these steps before you submit a PR.

- [ ] My Pod Leader knows I'm working on this Pull Request
- [ ] I've explained what the Pull Request is adding.
- [ ] I've explained why this is important.

Fixes #9

2023-03-11 15:20 UTC, sumana2001 requested changes
<img width="946" alt="Screenshot 2023-03-11 at 8 45 02 PM" src="https://user-images.githubusercontent.com/63084088/224492355-051494e6-9244-4d2a-8e90-592fab29c7a8.png">
In some screen sizes, it is not responsive

https://deploy-preview-27--mlh-prep-23-mar-prep-1-portfolio.netlify.app/fellowpages/koichi
Koichi's page is not working for some reason

https://deploy-preview-27--mlh-prep-23-mar-prep-1-portfolio.netlify.app/fellowPages/
Sana's page is linking to this link which is not found

2023-03-11 15:20 UTC, sumana2001 commented on Gemfile.lock
> +    eventmachine (1.2.7-x64-mingw32)
Please don't commit the Gemfile.lock file

2023-03-13 02:17 UTC, sumana2001 requested changes
The Gemfile.lock file shouldn't be deleted, just removed from the commit. Also please fix merge conflicts

2023-03-13 09:23 UTC, J0SAL commented
@sumana2001 can you please review the changes? Right now the Gemfile.lock is getting ignored cuz of .gitignore, is that expected behavior?

2023-03-13 09:49 UTC, J0SAL commented
I reverted the Gemfile.lock to the version before it was modified, does it work?

2023-03-13 09:51 UTC, merged